[LOCATION-9] Run handleCountryChange function at first form render
vtex-apps/shopper-location pull request #26
Opened 2022-04-06 17:36 UTC by Arturo777

[Related Ticket ](https://vtex-dev.atlassian.net/browse/LOCATION-9)
[Workspace to test](https://arturovtex--emdesign.myvtex.com/gildan-fleece-crewneck-sweatshirt/p?__bindingAddress=www.emdesign.bg/)

2022-04-08 19:42 UTC, arturmagalhaesjr requested changes
Please, describe what you did on the PR description, the problem that you are solving and the steps to test it.

2022-04-12 17:45 UTC, arturmagalhaesjr reviewed
LGTM, @wender or @polishq should approve it

2022-04-12 18:23 UTC, polishq requested changes

2022-04-12 18:23 UTC, polishq commented on react/components/LocationForm.tsx
> +      handleCountryChange({
Hmm, this results in a double dispatch being sent, and there might also be a race condition since the first dispatch changes the `location` object. If you read `location` immediately after that I'm not sure if you'll get the previous location or the new one. 

What if you simply replaced the first dispatch with the `handleCountryChange()` function, since that also sends the dispatch?

I'm also not sure about about this conditional earlier: 
```
if (location?.country?.value === '') {
    location.country.value = culture.country
  }
```
I know you didn't change this in the current PR, but I think it's bad practice to overwrite component state like this. Maybe this could be part of the `useEffect` logic as well - like if `currentAddress` has no country, use `culture.country` to set it before sending the dispatch.

2022-04-18 17:50 UTC, closed without merging

2022-05-02 14:40 UTC, Arturo777 commented
The issue can replicate now with the next steps:
0. make sure that browser permission location is denied.
1. go to a PDP page, Bulgaria store:
https://emdesign.myvtex.com/holna-garnitura-beta-245x174-sm/p?__bindingAddress=www.emdesign.bg/
2. Click on 'Добавяне на местоположение' on the right pane.
3. The only available field is the country selector
4. The only way to display the other fields is to select 'Румъния', then 'България' again.
All the fields need to be initially displayed.
Thank you!