Add removed lines for regionID
vtex-apps/shopper-location pull request #27
Opened 2022-04-12 13:07 UTC by albertm805

## Changes made:
- add removed lines for setRegionId

2022-04-13 14:37 UTC, polishq requested changes

2022-04-13 19:55 UTC, polishq requested changes

2022-04-13 19:55 UTC, polishq commented on react/index.tsx
> +  const { location } = useLocationState()
I'm not sure this would work 🤔 The LocationState is only relevant to the Change Location Form, as far as I know

2022-04-13 19:55 UTC, polishq commented on react/index.tsx
> +  const updateRegionID = async () => {
You could do something like this (not sure if the Address type is defined, but you get the idea):
```suggestion
  const updateRegionID = async (address: Address) => {
```
and then use the passed-in address to fill the `setRegionId` mutation variables. You might not even need to remove the validation.

2022-04-13 19:55 UTC, polishq commented on react/index.tsx
> +          updateRegionID()
To continue from the above comment, you would then do this:
```suggestion
          updateRegionID(addressFields)
```

2022-04-13 22:37 UTC, albertm805 commented on react/index.tsx
> +  const updateRegionID = async () => {
What if instead of using the typing and `addressFields` we could use the address from the `orderForm` using the `Address` query used up top?

2022-04-14 13:46 UTC, polishq requested changes

2022-04-14 13:46 UTC, polishq commented on react/index.tsx
> +  const updateRegionID = async () => {
I don't think that's necessary. You already have the new address since it was used to send the `updateAddress` mutation. If you were going to use the `orderForm` you would need to make sure to refetch it after sending the `updateAddress` mutation so that you have the newly updated address, and there might be a delay there. Better to use the same address that the mutation used, in my opinion.

2022-04-14 18:57 UTC, albertm805 commented on react/index.tsx
> +  const updateRegionID = async () => {
I updated the update region Address Passing to it only the necessary option used in the `updateRegion` function.

2022-04-14 20:13 UTC, polishq approved these changes
LGTM

2022-04-14 20:26 UTC, merged