[LOCATION-9] Run handleCountryChange function at first form render
vtex-apps/shopper-location pull request #28
Opened 2022-05-02 14:51 UTC by Arturo777

[Related Ticket](https://vtex-dev.atlassian.net/browse/LOCATION-9)
[Workspace to test](https://arturovtex--emdesign.myvtex.com/gildan-fleece-crewneck-sweatshirt/p?__bindingAddress=www.emdesign.bg/)

Description:
Client is using the shopper-location app and is experiencing a problem on the Bulgaria store. See steps to replicate the problem:

go to a [PDP page](https://arturovtex--emdesign.myvtex.com/holna-garnitura-belle-310x250-sm-kafyavo-i-bejovo/p?__bindingAddress=www.emdesign.ro/), Bulgaria store:
Click on add location on the right pane.
The only available field was the country selector
The only way to display the other fields was to select 'Romain', then 'Bulgarian' again.
All the fields needed to be initially displayed.
Now i put the function in charge to render the fields at the first form render.

2022-05-03 17:47 UTC, polishq requested changes

2022-05-03 17:47 UTC, polishq commented on react/components/LocationForm.tsx
>      if (isMountedRef.current) {
```suggestion
    if (isMountedRef.current && country) {
```

2022-05-03 17:47 UTC, polishq commented on react/index.tsx
>      // eslint-disable-next-line react-hooks/exhaustive-deps
Remove eslint-disable if possible

2022-05-03 17:47 UTC, polishq commented on react/index.tsx
>      // eslint-disable-next-line react-hooks/exhaustive-deps
Remove eslint-disable if possible

2022-05-04 15:33 UTC, Arturo777 commented on react/index.tsx
>      // eslint-disable-next-line react-hooks/exhaustive-deps
yeah, i didn't made this disable rule comment, but i removed already, i had to add `updateRegionID` to the array dependencies and wrap the function into its own callback function.

2022-05-04 15:34 UTC, Arturo777 commented on react/index.tsx
>      // eslint-disable-next-line react-hooks/exhaustive-deps
yeah, i didn't made this disable rule comment, but i removed already, i had to add updateRegionID to the array dependencies and wrap the function into its own callback function.

2022-05-04 17:39 UTC, polishq approved these changes

2022-05-04 17:44 UTC, merged